"""Personnel académique UNIKIN, charge horaire SGAC 2024-2025."""
PERSONNEL = (
    ('DENT', 'Faculté de Médecine dentaire', '', 'NTUMBA MULUMBA', 'PE', '', ''),
    ('DENT', 'Faculté de Médecine dentaire', '', 'SONGO BAUKAKA', 'PO', '', ''),
    ('DENT', 'Faculté de Médecine dentaire', '', 'LUTULA PENE', 'PR', '', ''),
    ('DENT', 'Faculté de Médecine dentaire', '', 'SEKELE ISOURADI', 'PR', '', ''),
    ('DENT', 'Faculté de Médecine dentaire', '', 'BOLENGE ILEBOSO', 'PR', '', ''),
    ('DENT', 'Faculté de Médecine dentaire', '', 'MANTSHUM MILOLO', 'PR', '', ''),
    ('DENT', 'Faculté de Médecine dentaire', '', 'BOBE ALIFI', 'PA', '', ''),
    ('DENT', 'Faculté de Médecine dentaire', '', 'MUYEMBI MWINAMIN', 'PA', '', ''),
    ('DENT', 'Faculté de Médecine dentaire', '', 'NYIMI BUSHABU', 'PA', '', ''),
    ('DENT', 'Faculté de Médecine dentaire', '', 'KALALA KAZADI', 'PA', '', ''),
    ('DENT', 'Faculté de Médecine dentaire', '', 'KUMPANYA NTUMBA', 'PA', '', ''),
    ('DENT', 'Faculté de Médecine dentaire', '', 'MFUTU MANA', 'PA', '', ''),
    ('DENT', 'Faculté de Médecine dentaire', '', 'KAYEMBE BUKAMA', 'PA', '', ''),
    ('DENT', 'Faculté de Médecine dentaire', '', 'LINDONDO ESABISH', 'PA', '', ''),
    ('DENT', 'Faculté de Médecine dentaire', 'David', 'KAYEMBE', 'PA', '', ''),
    ('DENT', 'Faculté de Médecine dentaire', '', 'BILE BOPILI', 'PA', '', ''),
    ('DENT', 'Faculté de Médecine dentaire', '', 'CHABO BYAENE', 'PA', '', ''),
    ('FMV', 'Faculté de Médecine vétérinaire', '', 'MULUMBA MFUMU KAZADI', 'PR', 'DOYEN', ''),
    ('DROIT', 'Faculté de Droit', 'Evariste', 'BOSHAB', 'PO', '', ''),
    ('DROIT', 'Faculté de Droit', '', 'KWETE MBUL', 'PO', '', ''),
    ('DROIT', 'Faculté de Droit', '', 'KALUBA DIBWA', 'PO', '', ''),
    ('DROIT', 'Faculté de Droit', '', 'NTUMBA MUSUKA', 'PO', '', ''),
    ('DROIT', 'Faculté de Droit', '', 'NGONDANKOY NKOY', 'PO', '', ''),
    ('DROIT', 'Faculté de Droit', '', 'MBOKO DJANDIMA', 'PO', '', ''),
    ('DROIT', 'Faculté de Droit', 'Willy', 'MAKIASHI', 'PR', '', ''),
    ('DROIT', 'Faculté de Droit', '', 'MBANGALA BIMBU', 'PR', '', ''),
    ('DROIT', 'Faculté de Droit', '', 'FIMPA TUWIZANA', 'PR', '', ''),
    ('DROIT', 'Faculté de Droit', '', 'MENDE OLENGA', 'PA', '', ''),
    ('DROIT', 'Faculté de Droit', '', 'ODIKO LOKANGAKA', 'PA', '', ''),
    ('DROIT', 'Faculté de Droit', '', 'MBAU SUKISA', 'PA', '', ''),
    ('DROIT', 'Faculté de Droit', 'Richard', 'TSHIENDA', 'PA', '', ''),
    ('DROIT', 'Faculté de Droit', '', 'EKOTO LOLEKE', 'PA', '', ''),
    ('DROIT', 'Faculté de Droit', 'Bobo', 'MULUMBA', 'PA', '', ''),
    ('DROIT', 'Faculté de Droit', 'Laurent', 'ONYEMBA', 'PA', '', ''),
    ('DROIT', 'Faculté de Droit', '', 'MPUTU ALOWA', 'PA', '', ''),
    ('DROIT', 'Faculté de Droit', '', 'KENGA BULOBA', 'PA', '', ''),
    ('DROIT', 'Faculté de Droit', '', 'BUSHAKE NGUASHO', 'PA', '', ''),
    ('DROIT', 'Faculté de Droit', '', 'LINGBANGBAO MIZO', 'PA', '', ''),
    ('DROIT', 'Faculté de Droit', '', 'NDOMBI KAMUANZA', 'DR', '', ''),
    ('DROIT', 'Faculté de Droit', 'Joseph', 'FUNDA', 'PO', '', ''),
    ('FPGEN', 'Faculté de Pétrole, Gaz et Énergies renouvelables', '', 'MATAMBA JIBIKILA RAPHAEL', 'PA', '', '18.001/7.952.278E'),
    ('FPGEN', 'Faculté de Pétrole, Gaz et Énergies renouvelables', '', 'KABAMBA BALUDIKAY BLAISE', 'PA', '', '18.746/7984949P'),
    ('FPGEN', 'Faculté de Pétrole, Gaz et Énergies renouvelables', '', 'DIANGITUKULU NDIMBA SAMUEL', 'PA', '', '7937851'),
    ('FPGEN', 'Faculté de Pétrole, Gaz et Énergies renouvelables', '', 'KAMPATA MBWELELE DONA', 'PR', '', '17.841/7.876.666A'),
    ('FPGEN', 'Faculté de Pétrole, Gaz et Énergies renouvelables', '', 'PINGO MUTOMBO', 'PR', '', '18 004/7 957 861 N'),
    ('FPGEN', 'Faculté de Pétrole, Gaz et Énergies renouvelables', 'Cyprien', 'MULUMBA TSHIENDA', 'PA', '', '19082/7947521 X'),
    ('FPGEN', 'Faculté de Pétrole, Gaz et Énergies renouvelables', '', 'MOLIBA BANKANJA', 'PA', '', '17301/7.940.850T'),
    ('FPGEN', 'Faculté de Pétrole, Gaz et Énergies renouvelables', '', 'BUKALO NTUMBA NENITA', 'DR', '', '21 453'),
    ('FPGEN', 'Faculté de Pétrole, Gaz et Énergies renouvelables', 'Nadège', 'MBULA NGOY', 'DR', '', 'Temps plein'),
    ('FPGEN', 'Faculté de Pétrole, Gaz et Énergies renouvelables', '', 'MAKUKU MBO LEVESQUE', 'PA', '', '17.040/7.933.746X'),
    ('FPGEN', 'Faculté de Pétrole, Gaz et Énergies renouvelables', '', 'NKODI MANANGA', 'PA', '', '18.453/7.969.743 N'),
    ('FPSE', "Faculté de Psychologie et des Sciences de l'Éducation", '', 'KUTUNGA NIJIKAP', 'PA', '', ''),
    ('FPSE', "Faculté de Psychologie et des Sciences de l'Éducation", '', 'KABONGO MUKINAYI', 'PR', '', ''),
    ('FPSE', "Faculté de Psychologie et des Sciences de l'Éducation", 'Florence', 'MBIYA MUADI', 'PR', '', ''),
    ('FPSE', "Faculté de Psychologie et des Sciences de l'Éducation", 'Jacqueline', 'BUKAKA BUNTANGU', 'PR', '', ''),
    ('FPSE', "Faculté de Psychologie et des Sciences de l'Éducation", '', 'KANDALA FANDIDI', 'PR', '', ''),
    ('FPSE', "Faculté de Psychologie et des Sciences de l'Éducation", '', 'NDJUKENDI OMBA', 'PA', '', ''),
    ('FPSE', "Faculté de Psychologie et des Sciences de l'Éducation", 'Gaston', 'KAPUKU MUDIPANU', 'PO', '', ''),
    ('FPSE', "Faculté de Psychologie et des Sciences de l'Éducation", 'Roger', 'MUSALU SIKISA', 'PR', '', ''),
    ('FPSE', "Faculté de Psychologie et des Sciences de l'Éducation", '', 'MAKUMOLE KIKOMINA', 'PA', '', ''),
    ('FPSE', "Faculté de Psychologie et des Sciences de l'Éducation", '', 'MANDIANGU MBUMBA', 'PR', '', ''),
    ('FPSE', "Faculté de Psychologie et des Sciences de l'Éducation", '', 'NTUNGA NAWANWA', 'PE', '', ''),
    ('FPSE', "Faculté de Psychologie et des Sciences de l'Éducation", '', 'DUAGANI MASIKA', 'PA', '', ''),
    ('FPSE', "Faculté de Psychologie et des Sciences de l'Éducation", '', 'MANWANINA KIUMBA', 'PR', '', ''),
    ('FPSE', "Faculté de Psychologie et des Sciences de l'Éducation", '', 'MONDJUMBU', 'PA', '', ''),
    ('FPSE', "Faculté de Psychologie et des Sciences de l'Éducation", '', 'MBADU KHONDE', 'PO', '', ''),
    ('FPSE', "Faculté de Psychologie et des Sciences de l'Éducation", '', 'NGOY AMBA', 'PA', '', ''),
    ('FPSE', "Faculté de Psychologie et des Sciences de l'Éducation", '', 'BUMBA MONGA NGOY', 'PE', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", '', 'KASONGO NUMBI', 'PE', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", '', 'BITIJULA MAHIMBA', 'PO', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", '', 'KACHAKA SUDI', 'PO', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", '', 'MAFUKA MBE MPIE', 'PO', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", '', 'TSHIMANGA MUAMBA', 'PO', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", '', 'LUMBUENAMO SINSI', 'PR', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", '', 'KAMATHE KATSONGO', 'PR', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", '', 'KIBAMBE LUBAMBA', 'PR', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", '', 'LELE NYAMI', 'PR', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", '', 'SEMEKI NGABINZEKE', 'PR', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", '', 'BWANGOY BANKANZA', 'PA', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", '', 'BOLALUEMBE BOLIALE', 'PA', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", '', 'BARAKA LUCUNGU', 'PA', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", '', 'KACHAKA YUSUFU', 'PA', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", '', 'OPELELE OMENO', 'PA', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", '', 'MAFWILA MBONA', 'PE', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", '', 'KIATOKO MANGEYE', 'PE', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", '', 'OKITAYELA ONAWOMA', 'PO', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", '', 'KAMBASHI MUTIAKA', 'PR', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", '', 'KIATOKO NKOBA', 'PA', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", '', 'TSHINYAMA NTUMBA', 'PA', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", '', 'KALALA BOLOKANGO', 'PA', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", 'Pierre', 'NSUMBU NLANDU', 'PE', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", 'Adrien', 'KALONJI MBUYI', 'PE', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", 'Joseph', 'KATANGA KABALEVI', 'PO', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", '', 'MOBAMBO KITUME NGONGO', 'PO', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", 'Marcel', 'MUENGULA MANYI', 'PR', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", 'Denis', 'BUNGU MULOMBO', 'PR', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", 'Nestor', 'ELEKO NDENGO', 'PA', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", 'Luc', 'TSHILENGE LUKANDA', 'PA', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", 'Augustin', 'NGOMBO NZOKWANI', 'PA', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", '', 'KHASA PAMBU', 'PR', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", '', 'MBENGA IBESOA', 'PR', '', ''),
    ('AGRO', "Faculté des Sciences agronomiques et de l'Environnement", '', 'MAFWILA KINKELA', 'PR', '', ''),
    ('PHARM', 'Faculté des Sciences pharmaceutiques', '', 'LIESSE IYAMBA', 'PR', '', ''),
    ('PHARM', 'Faculté des Sciences pharmaceutiques', '', 'MASIALA TSOBO', 'PR', '', ''),
    ('PHARM', 'Faculté des Sciences pharmaceutiques', '', 'NDELO DI-PHANZU', 'PR', '', ''),
    ('PHARM', 'Faculté des Sciences pharmaceutiques', '', 'NSIMBA MIEZI', 'PR', '', ''),
    ('PHARM', 'Faculté des Sciences pharmaceutiques', '', 'NUAPIA YANNICK', 'PR', '', ''),
    ('PHARM', 'Faculté des Sciences pharmaceutiques', '', 'ONOKODI KASONGO', 'PR', '', ''),
    ('PHARM', 'Faculté des Sciences pharmaceutiques', '', 'TAKAISI KIKUNI', 'PR', '', ''),
    ('SCI', 'Faculté des Sciences et Technologies', 'Médard', 'NTOMBI MWEN KABEYA', 'PE', '', ''),
    ('SCI', 'Faculté des Sciences et Technologies', 'Valentin', 'KANDA NKULA', 'PE', '', ''),
    ('SCI', 'Faculté des Sciences et Technologies', 'Jean Patrice', 'INTIOMALE MBONINO MOKFE', 'PO', '', ''),
    ('SCI', 'Faculté des Sciences et Technologies', 'Constantin', 'KAKESE KUNYIMA', 'PO', '', ''),
    ('SCI', 'Faculté des Sciences et Technologies', 'Albert', 'ONGENDANGENDA TSIENGE', 'PO', '', ''),
    ('SCI', 'Faculté des Sciences et Technologies', 'Thomas', 'KANIKA MAYENA', 'PO', '', ''),
    ('SCI', 'Faculté des Sciences et Technologies', 'Félicien', 'MITI TSETA', 'PE', '', ''),
    ('SCI', 'Faculté des Sciences et Technologies', '', 'NZUZI LELO', 'PO', '', ''),
    ('SCI', 'Faculté des Sciences et Technologies', 'Rubens', 'KOY KASONGO', 'PO', '', ''),
    ('SCI', 'Faculté des Sciences et Technologies', 'Dominique', 'WETSHONDO OSOMBA', 'PO', '', ''),
    ('SCI', 'Faculté des Sciences et Technologies', 'Modeste', 'KISANGALA MUKE', 'PR', '', ''),
    ('SCI', 'Faculté des Sciences et Technologies', 'Fils', 'MAKANZU IMWANGANA', 'PR', '', ''),
    ('SCI', 'Faculté des Sciences et Technologies', 'Holy', 'HOLENU MANGENDA', 'PR', '', ''),
    ('SCI', 'Faculté des Sciences et Technologies', 'Didier', 'YINA NGUNGA', 'PA', '', ''),
    ('SCI', 'Faculté des Sciences et Technologies', 'Serge', 'PANGU SANGHY', 'PR', '', ''),
)
