# Generated by Django 5.0.4 on 2026-09-23 18:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_motifpaiement_code_auto'),
        ('students', '0012_student_code_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=40, unique=True, verbose_name='Référence')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant')),
                ('devise', models.CharField(choices=[('USD', 'Dollars (USD)'), ('CDF', 'Francs congolais (CDF)')], default='USD', max_length=3, verbose_name='Devise')),
                ('mode', models.CharField(choices=[('especes', 'Espèces (caisse)'), ('mobile_money', 'Mobile money'), ('carte_bancaire', 'Carte bancaire')], default='especes', max_length=20, verbose_name='Mode de paiement')),
                ('operateur', models.CharField(blank=True, choices=[('airtel_money', 'Airtel Money'), ('m_pesa', 'M-Pesa'), ('orange_money', 'Orange Money'), ('afrimoney', 'Afrimoney')], max_length=20, verbose_name='Opérateur mobile money')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Numéro mobile money')),
                ('reference_transaction', models.CharField(blank=True, help_text='Code reçu par mobile money ou autorisation de la carte.', max_length=64, verbose_name='Référence de transaction')),
                ('carte_masquee', models.CharField(blank=True, help_text="Uniquement les 4 derniers chiffres. Le numéro complet n'est jamais enregistré.", max_length=4, verbose_name='4 derniers chiffres')),
                ('statut', models.CharField(choices=[('paye', 'Payé'), ('en_attente', 'En attente'), ('echoue', 'Échoué'), ('annule', 'Annulé')], default='paye', max_length=20, verbose_name='Statut')),
                ('date_paiement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du paiement')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='students.inscription', verbose_name='Inscription')),
                ('motif_paiement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='finance.motifpaiement', verbose_name='Frais')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement', '-pk'],
                'indexes': [models.Index(fields=['statut', 'mode'], name='finance_pai_statut_8d3e68_idx'), models.Index(fields=['date_paiement'], name='finance_pai_date_pa_45d0d7_idx')],
            },
        ),
    ]
