# Generated by Django 5.0.4 on 2026-09-23 18:13

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


def integrer_motifs_unikin(apps, schema_editor):
    MotifPaiement = apps.get_model('finance', 'MotifPaiement')
    AnneeAcademique = apps.get_model('academics', 'AnneeAcademique')
    from finance.motifs_unikin_data import MOTIFS_UNIKIN_2025

    annee = AnneeAcademique.objects.filter(code='2025-2026').first()
    if annee is None:
        return
    for row in MOTIFS_UNIKIN_2025:
        if MotifPaiement.objects.filter(
            annee_academique=annee,
            contexte=row['contexte'],
            semestre__isnull=True,
        ).exists():
            continue
        MotifPaiement.objects.create(
            annee_academique=annee,
            semestre=None,
            contexte=row['contexte'],
            code=row['code'],
            nom=row['nom'],
            description=row['description'],
            montant=Decimal(row['montant']),
            devise=row['devise'],
            ordre=row['ordre'],
            active=True,
        )


def retirer_motifs_unikin(apps, schema_editor):
    MotifPaiement = apps.get_model('finance', 'MotifPaiement')
    from finance.motifs_unikin_data import MOTIFS_UNIKIN_2025

    contextes = [row['contexte'] for row in MOTIFS_UNIKIN_2025]
    MotifPaiement.objects.filter(contexte__in=contextes, semestre__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_ordre_champs_simples'),
        ('finance', '0010_paiement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motifpaiement',
            options={'ordering': ['annee_academique__annee_debut', 'ordre', 'semestre__numero', 'contexte', 'nom'], 'verbose_name': 'Motif de paiement', 'verbose_name_plural': 'Motifs de paiement'},
        ),
        migrations.AlterUniqueTogether(
            name='motifpaiement',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='motifpaiement',
            name='contexte',
            field=models.CharField(choices=[('enrollement_session_principale', 'Enrôlement session principale'), ('enrollement_session_rattrapage', 'Enrôlement session rattrapage'), ('frais_inscription', "Frais d'inscription"), ('acad_recrutement', 'Frais académiques — classes de recrutement'), ('acad_montantes_1', 'Frais académiques — classes montantes, 1re tranche'), ('acad_montantes_2', 'Frais académiques — classes montantes, 2e tranche'), ('acad_etranger_rec', 'Frais académiques étrangers — recrutement'), ('acad_etranger_1', 'Frais académiques étrangers — 1re tranche'), ('acad_etranger_2', 'Frais académiques étrangers — 2e tranche')], default='enrollement_session_principale', max_length=40, verbose_name='Contexte'),
        ),
        migrations.AlterField(
            model_name='motifpaiement',
            name='semestre',
            field=models.ForeignKey(blank=True, help_text='Laissé vide pour un frais annuel (inscription, frais académiques).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motifs_paiement', to='academics.semestre', verbose_name='Semestre'),
        ),
        migrations.AddConstraint(
            model_name='motifpaiement',
            constraint=models.UniqueConstraint(condition=models.Q(('semestre__isnull', False)), fields=('annee_academique', 'semestre', 'contexte'), name='finance_motif_unique_semestre'),
        ),
        migrations.AddConstraint(
            model_name='motifpaiement',
            constraint=models.UniqueConstraint(condition=models.Q(('semestre__isnull', True)), fields=('annee_academique', 'contexte'), name='finance_motif_unique_annuel'),
        ),
        migrations.RunPython(integrer_motifs_unikin, retirer_motifs_unikin),
    ]
