# Generated by Django 5.2.11 on 2026-03-18 12:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('capacite', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacité')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locaux',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['code'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='departement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='departement',
            name='faculte',
        ),
        migrations.AlterUniqueTogether(
            name='parcours',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='parcours',
            name='filiere',
        ),
        migrations.AlterModelOptions(
            name='filiere',
            options={'ordering': ['section', 'code'], 'verbose_name': 'Filière', 'verbose_name_plural': 'Filières'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['filiere', 'ordre', 'code'], 'verbose_name': 'Promotion', 'verbose_name_plural': 'Promotions'},
        ),
        migrations.AddField(
            model_name='promotion',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='academics.filiere', verbose_name='Filière'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='ordre',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Code'),
        ),
        migrations.AlterUniqueTogether(
            name='promotion',
            unique_together={('filiere', 'code')},
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('nom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom')),
                ('effectif_max', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Effectif maximum')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academics.promotion', verbose_name='Promotion')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academics.local', verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['promotion', 'code'],
                'unique_together': {('promotion', 'code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='filiere',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='filiere',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='academics.section', verbose_name='Section'),
        ),
        migrations.AlterUniqueTogether(
            name='filiere',
            unique_together={('section', 'code')},
        ),
        migrations.DeleteModel(
            name='Faculte',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='annee_academique',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='effectif_max',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='parcours',
        ),
        migrations.RemoveField(
            model_name='filiere',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='filiere',
            name='niveau',
        ),
        migrations.DeleteModel(
            name='Parcours',
        ),
        migrations.DeleteModel(
            name='Departement',
        ),
    ]
