# Generated by Django 5.2.11 on 2026-05-19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_alter_card_public_token'),
        ('academics', '0002_local_section_alter_departement_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementconstitutif',
            name='professeur',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='elements_constitutifs',
                to='cards.personnel',
                verbose_name='Professeur',
            ),
        ),
    ]
