# Generated by Django 5.2.10 on 2026-06-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_elementconstitutif_professeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniteenseignement',
            name='categorie',
            field=models.CharField(choices=[('A', 'Catégorie A'), ('B', 'Catégorie B')], default='A', max_length=1, verbose_name='Catégorie'),
        ),
    ]
