# Generated by Django 5.0.4 on 2026-09-22 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_ec_note_eliminatoire'),
        ('config', '0002_etablissement_national'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['etablissement', 'code'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AddField(
            model_name='section',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='config.etablissement', verbose_name='Établissement'),
        ),
        migrations.AlterField(
            model_name='section',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Code'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(condition=models.Q(('etablissement__isnull', True)), fields=('code',), name='uniq_section_code_sans_etablissement'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(condition=models.Q(('etablissement__isnull', False)), fields=('etablissement', 'code'), name='uniq_section_code_par_etablissement'),
        ),
    ]
