# Generated by Django 5.0.4 on 2026-09-22 17:07

import django.db.models.deletion
from django.db import migrations, models


FACULTES_UNIKIN = (
    ('DROIT', 'Faculté de Droit'),
    ('SEG', 'Faculté des Sciences Économiques et de Gestion'),
    ('FSSAP', 'Faculté des Sciences Sociales, Administratives et Politiques'),
    ('FPSE', 'Faculté de Psychologie et des Sciences de l\'Éducation'),
    ('LSH', 'Faculté des Lettres et Sciences Humaines'),
    ('SCI', 'Faculté des Sciences'),
    ('POLY', 'Faculté Polytechnique'),
    ('MED', 'Faculté de Médecine'),
    ('PHARM', 'Faculté de Pharmacie'),
    ('AGRO', 'Faculté des Sciences Agronomiques'),
    ('FMV', 'Faculté de Médecine Vétérinaire'),
    ('FPGEN', 'Faculté de Pétrole, Gaz et Énergies Nouvelles'),
)


def seed_facultes_unikin(apps, schema_editor):
    Etablissement = apps.get_model('config', 'Etablissement')
    Faculte = apps.get_model('academics', 'Faculte')
    unikin = Etablissement.objects.filter(code='UNIKIN').first()
    if unikin is None:
        return
    for code, nom in FACULTES_UNIKIN:
        Faculte.objects.get_or_create(
            etablissement=unikin,
            code=code,
            defaults={'nom': nom, 'active': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_etablissement_national'),
        ('config', '0002_etablissement_national'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Sigle')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facultes', to='config.etablissement', verbose_name='Établissement')),
            ],
            options={
                'verbose_name': 'Faculté',
                'verbose_name_plural': 'Facultés',
                'ordering': ['etablissement', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='filiere',
            name='faculte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filieres', to='academics.faculte', verbose_name='Faculté'),
        ),
        migrations.AddConstraint(
            model_name='faculte',
            constraint=models.UniqueConstraint(fields=('etablissement', 'code'), name='uniq_faculte_code_par_etablissement'),
        ),
        migrations.RunPython(seed_facultes_unikin, migrations.RunPython.noop),
    ]
