# Generated by Django 5.0.4 on 2026-09-22 17:17

import django.db.models.deletion
from django.db import migrations, models


DEPARTEMENTS_DROIT = (
    ('DPJ', 'Droit privé et judiciaire'),
    ('DPC', 'Droit pénal et criminologie'),
    ('DEA', 'Droit économique et des affaires'),
    ('DPI', 'Droit public interne'),
    ('DIPA', 'Droit international public et africain'),
    ('DDH', "Droit des droits de l'homme"),
    ('DEDD', "Droit de l'environnement et développement durable"),
)


def seed_departements_droit(apps, schema_editor):
    Faculte = apps.get_model('academics', 'Faculte')
    Departement = apps.get_model('academics', 'Departement')
    droit = Faculte.objects.filter(etablissement__code='UNIKIN', code='DROIT').first()
    if droit is None:
        return
    for code, nom in DEPARTEMENTS_DROIT:
        Departement.objects.get_or_create(
            faculte=droit,
            code=code,
            defaults={'nom': nom, 'active': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_facultes_unikin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Sigle')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departements', to='academics.faculte', verbose_name='Faculté')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['faculte', 'nom'],
            },
        ),
        migrations.AddConstraint(
            model_name='departement',
            constraint=models.UniqueConstraint(fields=('faculte', 'code'), name='uniq_departement_code_par_faculte'),
        ),
        migrations.RunPython(seed_departements_droit, migrations.RunPython.noop),
    ]
