# Generated by Django 5.0.4 on 2026-09-22 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_departements_facultes_unikin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filiere',
            options={'ordering': ['faculte', 'departement', 'code'], 'verbose_name': 'Filière', 'verbose_name_plural': 'Filières'},
        ),
        migrations.AddField(
            model_name='filiere',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='filieres', to='academics.departement', verbose_name='Département'),
        ),
        migrations.AddConstraint(
            model_name='filiere',
            constraint=models.UniqueConstraint(condition=models.Q(('departement__isnull', False)), fields=('departement', 'code'), name='uniq_filiere_code_par_departement'),
        ),
    ]
