# Generated by Django 5.0.4 on 2026-09-23 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_filieres_unikin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='local',
            field=models.ForeignKey(blank=True, help_text="Salle, lorsqu'elle est déjà attribuée. La lettre de classe (A, B, …) suffit pour identifier l'étudiant.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academics.local', verbose_name='Local'),
        ),
    ]
