# Generated by Django 5.0.4 on 2026-09-23 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_promotions_unikin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['promotion_id', 'code'], 'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='departement',
            options={'ordering': ['faculte_id', 'nom'], 'verbose_name': 'Département', 'verbose_name_plural': 'Départements'},
        ),
        migrations.AlterModelOptions(
            name='faculte',
            options={'ordering': ['etablissement_id', 'nom'], 'verbose_name': 'Faculté', 'verbose_name_plural': 'Facultés'},
        ),
        migrations.AlterModelOptions(
            name='filiere',
            options={'ordering': ['faculte_id', 'departement_id', 'code'], 'verbose_name': 'Filière', 'verbose_name_plural': 'Filières'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['filiere_id', 'ordre', 'code'], 'verbose_name': 'Promotion', 'verbose_name_plural': 'Promotions'},
        ),
    ]
