# Generated by Django 5.2.10 on 2026-01-23 18:04

import django.core.validators
import django.db.models.deletion
import students.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('obligatoire', models.BooleanField(default=True, verbose_name='Obligatoire')),
                ('ordre', models.IntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Type de document',
                'verbose_name_plural': 'Types de documents',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inscription', models.CharField(max_length=50, unique=True, verbose_name="Numéro d'inscription")),
                ('date_inscription', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('statut', models.CharField(choices=[('preinscrit', 'Pré-inscrit'), ('inscrit', 'Inscrit'), ('reinscrit', 'Réinscrit'), ('redoublant', 'Redoublant'), ('transfert', 'Transfert'), ('desinscrit', 'Désinscrit')], default='preinscrit', max_length=20, verbose_name='Statut')),
                ('frais_inscription', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Frais d'inscription")),
                ('frais_payes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Frais payés')),
                ('dossier_complet', models.BooleanField(default=False, verbose_name='Dossier complet')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='academics.anneeacademique', verbose_name='Année académique')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='academics.promotion', verbose_name='Promotion')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-annee_academique', 'etudiant'],
            },
        ),
        migrations.CreateModel(
            name='DossierEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ouverture', models.DateField(auto_now_add=True, verbose_name="Date d'ouverture")),
                ('date_fermeture', models.DateField(blank=True, null=True, verbose_name='Date de fermeture')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('complet', 'Complet'), ('incomplet', 'Incomplet'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inscription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dossier', to='students.inscription', verbose_name='Inscription')),
            ],
            options={
                'verbose_name': 'Dossier étudiant',
                'verbose_name_plural': 'Dossiers étudiants',
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_etudiant', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro étudiant doit contenir uniquement des lettres majuscules et des chiffres', regex='^[A-Z0-9]+$')], verbose_name='Numéro étudiant')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=200, verbose_name='Lieu de naissance')),
                ('nationalite', models.CharField(default='Algérienne', max_length=100, verbose_name='Nationalité')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=students.models.student_photo_path, verbose_name='Photo')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('exclu', 'Exclu'), ('diplome', 'Diplômé'), ('abandon', 'Abandon')], default='actif', max_length=20, verbose_name='Statut')),
                ('date_inscription', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['numero_etudiant'],
            },
        ),
        migrations.AddField(
            model_name='inscription',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='students.student', verbose_name='Étudiant'),
        ),
        migrations.CreateModel(
            name='DocumentEtudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=students.models.document_path, verbose_name='Fichier')),
                ('date_depot', models.DateField(auto_now_add=True, verbose_name='Date de dépôt')),
                ('valide', models.BooleanField(default=False, verbose_name='Validé')),
                ('date_validation', models.DateField(blank=True, null=True, verbose_name='Date de validation')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.inscription', verbose_name='Inscription')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student', verbose_name='Étudiant')),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.typedocument', verbose_name='Type de document')),
            ],
            options={
                'verbose_name': 'Document étudiant',
                'verbose_name_plural': 'Documents étudiants',
                'ordering': ['-date_depot'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('etudiant', 'promotion', 'annee_academique')},
        ),
    ]
