# Generated by Django 5.2.11 on 2026-03-18 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_local_section_alter_departement_unique_together_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inscriptions', to='academics.classe', verbose_name='Classe'),
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('etudiant', 'classe', 'annee_academique')},
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='promotion',
        ),
    ]
