# Generated by Django 5.0.4 on 2026-06-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_inscription_unique_together_inscription_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nationalite',
            field=models.CharField(choices=[('Congolaise', 'Congolaise'), ('Algérienne', 'Algérienne'), ('Angolaise', 'Angolaise'), ('Béninoise', 'Béninoise'), ('Burkinabè', 'Burkinabè'), ('Burundaise', 'Burundaise'), ('Camerounaise', 'Camerounaise'), ('Centrafricaine', 'Centrafricaine'), ('Comorienne', 'Comorienne'), ('Djiboutienne', 'Djiboutienne'), ('Égyptienne', 'Égyptienne'), ('Éthiopienne', 'Éthiopienne'), ('Française', 'Française'), ('Gabonaise', 'Gabonaise'), ('Gambienne', 'Gambienne'), ('Ghanéenne', 'Ghanéenne'), ('Guinéenne', 'Guinéenne'), ('Ivoirienne', 'Ivoirienne'), ('Malienne', 'Malienne'), ('Marocaine', 'Marocaine'), ('Mauritanienne', 'Mauritanienne'), ('Nigériane', 'Nigériane'), ('Nigérienne', 'Nigérienne'), ('Ougandaise', 'Ougandaise'), ('Rwandaise', 'Rwandaise'), ('Sénégalaise', 'Sénégalaise'), ('Soudanaise', 'Soudanaise'), ('Tchadienne', 'Tchadienne'), ('Togolaise', 'Togolaise'), ('Tunisienne', 'Tunisienne'), ('Autre', 'Autre')], default='Congolaise', max_length=100, verbose_name='Nationalité'),
        ),
    ]
