# Generated by Django 5.0.4 on 2026-06-14 00:39

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_nationalite_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentetudiant',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to=students.models.document_path, verbose_name='Fichier'),
        ),
    ]
