# Generated by Django 5.0.4 on 2026-06-15 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_document_fichier_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='numero_etudiant',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Matricule invalide. Format : année + C (conception) ou R (réseaux) + n° à 3 chiffres (ex. 2026R001)', regex='^\\d{4}[RC]\\d{3}$')], verbose_name='Numéro étudiant'),
        ),
    ]
