# Generated by Django 5.0.4 on 2026-06-24 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_inscription_abandon_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='numero_etudiant',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Matricule invalide. Pre-Master / Master RX : année de début + n° à 3 chiffres (ex. 2024001, 2025001). Master CSI : année de fin + C + n° à 3 chiffres (ex. 2026C001).', regex='^(\\d{7}|\\d{4}[RC]\\d{3})$')], verbose_name='Numéro étudiant'),
        ),
    ]
