# Generated by Django 5.0.4 on 2026-09-22 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_etablissement_national'),
        ('students', '0010_matricule_unifie'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='config.etablissement', verbose_name='Établissement'),
        ),
    ]
