# Generated by Django 5.0.4 on 2026-07-06 18:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_uniteenseignement_filiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementconstitutif',
            name='note_eliminatoire',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si renseignée, une note EC strictement inférieure bloque la validation et la compensation.', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))], verbose_name='Note éliminatoire (/20)'),
        ),
    ]
