# Generated by Django 5.0.4 on 2026-06-24 11:40

import django.db.models.deletion
import projets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0006_uniteenseignement_filiere'),
        ('students', '0009_alter_student_numero_etudiant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300, verbose_name='Titre du projet')),
                ('resume', models.TextField(blank=True, verbose_name='Résumé')),
                ('mots_cles', models.CharField(blank=True, help_text='Séparés par des virgules', max_length=500, verbose_name='Mots-clés')),
                ('tuteur', models.CharField(blank=True, max_length=200, verbose_name='Tuteur')),
                ('date_finalisation', models.DateField(blank=True, null=True, verbose_name='Date de finalisation')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('finalise', 'Finalisé')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('fichier', models.FileField(blank=True, null=True, upload_to=projets.models.projet_fichier_path, verbose_name='Document (PDF, etc.)')),
                ('lien_externe', models.URLField(blank=True, verbose_name='Lien externe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets_academiques', to='academics.anneeacademique', verbose_name='Année académique')),
                ('element_constitutif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_academiques', to='academics.elementconstitutif', verbose_name='Élément constitutif')),
                ('etudiants', models.ManyToManyField(blank=True, related_name='projets_academiques', to='students.student', verbose_name='Étudiants')),
                ('filiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_academiques', to='academics.filiere', verbose_name='Filière')),
                ('semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_academiques', to='academics.semestre', verbose_name='Semestre')),
            ],
            options={
                'verbose_name': 'Projet académique',
                'verbose_name_plural': 'Projets académiques',
                'ordering': ['-date_finalisation', '-created_at'],
                'permissions': [('consulter_projets_finalises', 'Consulter les projets académiques finalisés')],
            },
        ),
    ]
