# Generated by Django 5.2.11 on 2026-02-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('position', models.CharField(max_length=150, verbose_name='Poste / Fonction')),
                ('category', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('education_level', models.CharField(max_length=100, verbose_name="Niveau d'études")),
                ('issue_date', models.DateField(verbose_name='Date de délivrance')),
                ('expiry_date', models.DateField(verbose_name="Date d'expiration")),
                ('card_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de carte / Matricule')),
                ('photo', models.ImageField(upload_to='cards/photos/', verbose_name='Photo de profil')),
                ('generated_card', models.ImageField(blank=True, null=True, upload_to='cards/generated/', verbose_name='Carte générée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carte PVC',
                'verbose_name_plural': 'Cartes PVC',
                'ordering': ['-created_at'],
            },
        ),
    ]
