# Generated by Django 5.2.11 on 2026-02-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_category_position_alter_card_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='generated_card_back',
            field=models.ImageField(blank=True, null=True, upload_to='cards/generated_back/', verbose_name='Carte générée (Verso)'),
        ),
        migrations.AlterField(
            model_name='card',
            name='generated_card',
            field=models.ImageField(blank=True, null=True, upload_to='cards/generated/', verbose_name='Carte générée (Recto)'),
        ),
    ]
