# Generated by Django 5.2.11 on 2026-02-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_generated_card_back_alter_card_generated_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='training_division_chief_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Chef des divisions Formation (Nom)'),
        ),
        migrations.AddField(
            model_name='card',
            name='training_division_chief_signature',
            field=models.ImageField(blank=True, null=True, upload_to='cards/signatures/', verbose_name='Signature Chef divisions Formation (image)'),
        ),
    ]
