# Generated by Django 5.2.11 on 2026-02-23 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_training_division_chief_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='training_division_chief_name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='training_division_chief_signature',
        ),
    ]
