# Generated by Django 5.2.11 on 2026-02-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_remove_card_training_division_chief_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_division_chief_name', models.CharField(blank=True, default='Chef des divisions Formation', max_length=150, null=True, verbose_name='Nom du Chef des divisions Formation')),
                ('training_division_chief_signature', models.ImageField(blank=True, null=True, upload_to='cards/signatures/', verbose_name='Signature (image) Chef divisions Formation')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
