# Generated by Django 5.2.11 on 2026-02-23 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_cardsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsettings',
            name='training_division_chief_title',
            field=models.CharField(default='Chef des divisions Formation', max_length=150, verbose_name='Titre affiché sous la photo'),
        ),
    ]
