# Generated by Django 5.2.11 on 2026-03-08 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_cardsettings_training_division_chief_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='card',
            name='category',
        ),
        migrations.RemoveField(
            model_name='card',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='card',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='card',
            name='position',
        ),
        migrations.AlterField(
            model_name='cardsettings',
            name='training_division_chief_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom du Chef des divisions Formation'),
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('education_level', models.CharField(max_length=100, verbose_name="Niveau d'études")),
                ('matricule', models.CharField(blank=True, max_length=50, null=True, verbose_name='Matricule')),
                ('photo', models.ImageField(upload_to='personnel/photos/', verbose_name='Photo de profil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.category', verbose_name='Catégorie')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.position', verbose_name='Poste / Fonction')),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnels',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.personnel', verbose_name='Personnel'),
        ),
    ]
