# Generated by Django 5.2.11 on 2026-03-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_remove_card_card_number_remove_card_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardsettings',
            name='digital_seal',
            field=models.ImageField(blank=True, null=True, upload_to='cards/seals/', verbose_name='Sceau numérique'),
        ),
    ]
