# Generated by Django 5.2.11 on 2026-03-29 17:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_cardsettings_digital_seal'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token public'),
        ),
    ]
