# Generated by Django 5.2.12 on 2026-03-29 18:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_card_public_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='public_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
