# Generated by Django 5.1.7 on 2026-05-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_alter_card_public_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='admin_function',
            field=models.CharField(blank=True, max_length=150, verbose_name='Fonction'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='admin_observations',
            field=models.TextField(blank=True, verbose_name='Observations'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='admin_received_by',
            field=models.CharField(blank=True, max_length=150, verbose_name='Dossier reçu par'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='admin_received_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de réception'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='admin_signature_stamp',
            field=models.CharField(blank=True, max_length=200, verbose_name='Signature et cachet'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='assignment_service',
            field=models.CharField(blank=True, max_length=150, verbose_name="Service d'affectation"),
        ),
        migrations.AddField(
            model_name='personnel',
            name='category_other',
            field=models.CharField(blank=True, max_length=150, verbose_name='Préciser la catégorie'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='contract_copy_attached',
            field=models.BooleanField(default=False, verbose_name="Copie de l'acte d'engagement / contrat"),
        ),
        migrations.AddField(
            model_name='personnel',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='personnel/contracts/', verbose_name='Upload copie du contrat'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='contract_reference',
            field=models.CharField(blank=True, max_length=200, verbose_name="Référence de l'acte d'engagement / contrat"),
        ),
        migrations.AddField(
            model_name='personnel',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('permanent', 'Permanent'), ('temporary', 'Temporaire'), ('vacataire', 'Vacataire')], max_length=20, verbose_name='Type de contrat'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='current_address',
            field=models.TextField(blank=True, verbose_name='Adresse actuelle'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Adresse e-mail'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='engagement_confirmed',
            field=models.BooleanField(default=False, verbose_name="Confirmation de l'engagement"),
        ),
        migrations.AddField(
            model_name='personnel',
            name='function_quality',
            field=models.CharField(blank=True, max_length=150, verbose_name='Fonction / Qualité'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='grade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='identity_photo_digital',
            field=models.BooleanField(default=False, verbose_name="Photo d'identité récente format numérique"),
        ),
        migrations.AddField(
            model_name='personnel',
            name='identity_photo_physical',
            field=models.BooleanField(default=False, verbose_name="Photo d'identité récente format physique"),
        ),
        migrations.AddField(
            model_name='personnel',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Célibataire'), ('married', 'Marié(e)'), ('divorced', 'Divorcé(e)'), ('widowed', 'Veuf/Veuve')], max_length=20, verbose_name='État civil'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='name_signature',
            field=models.CharField(blank=True, max_length=150, verbose_name='Noms et signature'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nationalité'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='other_pieces_attached',
            field=models.BooleanField(default=False, verbose_name='Autres pièces'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='other_pieces_details',
            field=models.TextField(blank=True, verbose_name='Préciser les autres pièces'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='other_pieces_file',
            field=models.FileField(blank=True, null=True, upload_to='personnel/other_pieces/', verbose_name='Upload autres pièces'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=150, verbose_name='Lieu de naissance'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='place_signed',
            field=models.CharField(default='Kinshasa', max_length=100, verbose_name='Fait à'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='service_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de prise de service'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='signature_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de signature'),
        ),
    ]
