# Generated by Django 5.2.10 on 2026-01-23 18:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('coefficient', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Coefficient par défaut')),
                ('note_max', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('20.00'))], verbose_name='Note maximale')),
                ('ordre', models.IntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': "Type d'évaluation",
                'verbose_name_plural': "Types d'évaluation",
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='Numéro de session')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('date_deliberation', models.DateField(blank=True, null=True, verbose_name='Date de délibération')),
                ('deliberation_faite', models.BooleanField(default=False, verbose_name='Délibération effectuée')),
                ('verrouillee', models.BooleanField(default=False, verbose_name='Session verrouillée')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academics.semestre', verbose_name='Semestre')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['semestre', 'numero'],
                'unique_together': {('semestre', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('date_evaluation', models.DateField(verbose_name="Date d'évaluation")),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Coefficient')),
                ('note_max', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('20.00'))], verbose_name='Note maximale')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academics.elementconstitutif', verbose_name='Élément Constitutif')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='evaluations.session', verbose_name='Session')),
                ('type_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='evaluations.typeevaluation', verbose_name="Type d'évaluation")),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['session', 'ec', 'type_evaluation'],
                'unique_together': {('ec', 'session', 'type_evaluation')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))], verbose_name='Note (/20)')),
                ('note_sur', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Note sur')),
                ('absent', models.BooleanField(default=False, verbose_name='Absent')),
                ('justifie', models.BooleanField(default=False, verbose_name='Absence justifiée')),
                ('justificatif', models.TextField(blank=True, null=True, verbose_name='Justificatif')),
                ('date_saisie', models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='students.student', verbose_name='Étudiant')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_etudiants', to='evaluations.evaluation', verbose_name='Évaluation')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_modifiees', related_query_name='note_modifiee', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('saisie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_saisies', to=settings.AUTH_USER_MODEL, verbose_name='Saisie par')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['evaluation', 'etudiant'],
                'unique_together': {('etudiant', 'evaluation')},
            },
        ),
        migrations.CreateModel(
            name='NoteUE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_finale', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))], verbose_name='Note finale (/20)')),
                ('credits_obtenus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Crédits obtenus')),
                ('valide', models.BooleanField(default=False, verbose_name='UE validée')),
                ('capitalise', models.BooleanField(default=False, verbose_name='UE capitalisée')),
                ('calculee_auto', models.BooleanField(default=True, verbose_name='Calculée automatiquement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_ue', to='students.student', verbose_name='Étudiant')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_etudiants', to='academics.uniteenseignement', verbose_name="Unité d'Enseignement")),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_ue', to='evaluations.session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Note UE',
                'verbose_name_plural': 'Notes UE',
                'ordering': ['session', 'ue', 'etudiant'],
                'unique_together': {('etudiant', 'ue', 'session')},
            },
        ),
        migrations.CreateModel(
            name='NoteEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_finale', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))], verbose_name='Note finale (/20)')),
                ('credits_obtenus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Crédits obtenus')),
                ('valide', models.BooleanField(default=False, verbose_name='EC validé')),
                ('capitalise', models.BooleanField(default=False, verbose_name='EC capitalisé')),
                ('calculee_auto', models.BooleanField(default=True, verbose_name='Calculée automatiquement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_etudiants', to='academics.elementconstitutif', verbose_name='Élément Constitutif')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_ec', to='students.student', verbose_name='Étudiant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_ec', to='evaluations.session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Note EC',
                'verbose_name_plural': 'Notes EC',
                'ordering': ['session', 'ec', 'etudiant'],
                'unique_together': {('etudiant', 'ec', 'session')},
            },
        ),
    ]
