# Generated by Django 5.2.11 on 2026-02-23 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-date_saisie'], 'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
    ]
