# Generated by Django 5.0.4 on 2026-07-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0004_session_evaluation_annee_academique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-annee_academique__annee_debut', 'semestre', 'numero'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
    ]
