# Generated by Django 5.2.10 on 2026-07-14 11:43

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import formation_continue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(blank=True, max_length=40, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('specialite', models.CharField(blank=True, max_length=150, verbose_name='Spécialité')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Formateur',
                'verbose_name_plural': 'Formateurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='ModuleTIC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('intitule', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duree_heures', models.PositiveIntegerField(default=0, verbose_name='Durée (heures)')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Module TIC',
                'verbose_name_plural': 'Modules TIC',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Seminariste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_participant', models.CharField(choices=[('fonctionnaire', 'Fonctionnaire (recommandé Admin. finances)'), ('independant', 'Indépendant')], max_length=20, verbose_name='Type')),
                ('matricule', models.CharField(blank=True, max_length=50, verbose_name='Matricule / N° dossier')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(blank=True, max_length=40, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('organisation', models.CharField(blank=True, help_text='Direction ou structure d’appartenance (fonctionnaires)', max_length=200, verbose_name='Organisation / Service')),
                ('recommande_par', models.CharField(blank=True, help_text='Administration des finances ou autorité de tutelle', max_length=200, verbose_name='Recommandé par')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Séminariste',
                'verbose_name_plural': 'Séminaristes',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='SessionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(help_text='Année civile de référence (ex. 2026)', verbose_name='Année')),
                ('numero', models.PositiveSmallIntegerField(help_text='De 1 à 4 (une session = 4 mois)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='N° de session')),
                ('libelle', models.CharField(max_length=120, verbose_name='Libellé')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session de formation',
                'verbose_name_plural': 'Sessions de formation',
                'ordering': ['-annee', 'numero'],
                'unique_together': {('annee', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='OffreModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Début du module')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Fin du module')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offres', to='formation_continue.formateur', verbose_name='Formateur')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offres', to='formation_continue.moduletic', verbose_name='Module')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='formation_continue.sessionformation', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Offre de module',
                'verbose_name_plural': 'Offres de modules',
                'ordering': ['session', 'module__code'],
                'unique_together': {('session', 'module')},
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date d’inscription')),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('abandon', 'Abandon')], default='inscrit', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modules', models.ManyToManyField(blank=True, related_name='inscriptions', to='formation_continue.offremodule', verbose_name='Modules suivis')),
                ('seminariste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='formation_continue.seminariste', verbose_name='Séminariste')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='formation_continue.sessionformation', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['-date_inscription', 'seminariste__nom'],
                'unique_together': {('seminariste', 'session')},
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seance', models.DateField(verbose_name='Date de séance')),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'Retard'), ('excuse', 'Excusé')], default='present', max_length=20, verbose_name='Statut')),
                ('remarque', models.CharField(blank=True, max_length=255, verbose_name='Remarque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='formation_continue.inscription', verbose_name='Inscription')),
                ('offre_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='formation_continue.offremodule', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-date_seance', 'inscription__seminariste__nom'],
                'unique_together': {('inscription', 'offre_module', 'date_seance')},
            },
        ),
        migrations.CreateModel(
            name='Brevet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=60, unique=True, verbose_name='N° de brevet')),
                ('date_delivrance', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date de délivrance')),
                ('fichier', models.FileField(blank=True, null=True, upload_to=formation_continue.models.brevet_upload_path, verbose_name='Fichier PDF')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modules_valides', models.ManyToManyField(blank=True, related_name='brevets', to='formation_continue.moduletic', verbose_name='Modules validés')),
                ('seminariste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brevets', to='formation_continue.seminariste', verbose_name='Séminariste')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brevets', to='formation_continue.sessionformation', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Brevet',
                'verbose_name_plural': 'Brevets',
                'ordering': ['-date_delivrance', 'numero'],
                'unique_together': {('seminariste', 'session')},
            },
        ),
    ]
