# Generated by Django 5.2.10 on 2026-07-14 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_continue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionformation',
            options={'ordering': ['-annee', 'numero'], 'permissions': [('cloturer_sessionformation', 'Peut clôturer une session de formation')], 'verbose_name': 'Session de formation', 'verbose_name_plural': 'Sessions de formation'},
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='cloturee',
            field=models.BooleanField(default=False, verbose_name='Clôturée'),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='cloturee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_fc_cloturees', to=settings.AUTH_USER_MODEL, verbose_name='Clôturée par'),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='date_cloture',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture'),
        ),
        migrations.AddField(
            model_name='sessionformation',
            name='observations_cloture',
            field=models.TextField(blank=True, verbose_name='Observations de clôture'),
        ),
    ]
