# Generated by Django 5.2.10 on 2026-07-14 12:24

import formation_continue.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formation_continue', '0002_session_cloture'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminariste',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=formation_continue.models.seminariste_photo_path, verbose_name='Photo'),
        ),
    ]
