# Generated by Django 5.2.11 on 2026-04-06 18:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_local_section_alter_departement_unique_together_and_more'),
        ('cards', '0011_alter_card_public_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(default="DIRECTION DES SYSTEMES D'INFORMATION", max_length=255, verbose_name='Direction')),
                ('ecole', models.CharField(default='ECOLE INFORMATIQUE DES FINANCES', max_length=255, verbose_name='École')),
                ('systeme', models.CharField(default='SYSTÈME LMD/RESEAU', max_length=255, verbose_name='Système')),
                ('titre', models.CharField(default="Horaire des unités d'enseignement", max_length=255, verbose_name='Titre')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observation')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horaires', to='academics.anneeacademique', verbose_name='Année académique')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='horaires', to='academics.classe', verbose_name='Classe')),
                ('semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='horaires', to='academics.semestre', verbose_name='Semestre')),
            ],
            options={
                'verbose_name': 'Horaire',
                'verbose_name_plural': 'Horaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HoraireLigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi')], max_length=20, verbose_name='Jour')),
                ('heure_debut', models.TimeField(verbose_name='Heure début')),
                ('heure_fin', models.TimeField(verbose_name='Heure fin')),
                ('ue_code', models.CharField(blank=True, max_length=50, verbose_name='Code UE')),
                ('ordre', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ordre')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('element_constitutif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horaire_lignes', to='academics.elementconstitutif', verbose_name='Élément constitutif')),
                ('horaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='prestation.horaire', verbose_name='Horaire')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horaire_lignes', to='academics.local', verbose_name='Local')),
                ('professeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horaire_lignes', to='cards.personnel', verbose_name='Professeur')),
            ],
            options={
                'verbose_name': "Ligne d'horaire",
                'verbose_name_plural': "Lignes d'horaire",
                'ordering': ['horaire', 'jour', 'heure_debut', 'ordre'],
            },
        ),
    ]
