# Generated by Django 5.2.11 on 2026-04-07 14:20

from django.db import migrations, models


def seed_baremes(apps, schema_editor):
    BaremePrestation = apps.get_model("prestation", "BaremePrestation")

    rows = [
        # Enseignement
        ("01", "enseignement", "Professeur, Docteur à thèse", 65000, 1),
        ("02", "enseignement", "Licencié avec DES, Ingénieur informaticien", 52500, 2),
        ("03", "enseignement", "Licencié, Analyste programmeur ou équivalent", 50000, 3),
        ("04", "enseignement", "Assistant, Gradué", 40500, 4),
        ("05", "enseignement", "Chargé des TP / TD", 32500, 5),
        # Activités académiques
        ("06", "academique", "Surveillance examens / interrogations", 6500, 1),
        ("07", "academique", "Correction examens", 65000, 2),
        ("08", "academique", "Correction interrogations", 50000, 3),
        ("09", "academique", "Délibération examens", 52500, 4),
        ("10", "academique", "Réunions pédagogiques", 50000, 5),
        ("11", "academique", "Encadrement de stages", 50000, 6),
        ("12", "academique", "Conférences / Séminaires", 65000, 7),
        ("13", "academique", "Supervision et encadrement scientifique (enseignant)", 16500, 8),
        ("18", "academique", "Supervision et encadrement administratif", 10000, 9),
        # Jury et soutenance
        ("14", "jury", "Directeur de mémoire & Président du jury", 262500, 1),
        ("15", "jury", "Rapporteur", 156500, 2),
        ("16", "jury", "Bureau du jury", 120000, 3),
        # Logistique
        ("17", "logistique", "10 litres de carburant / vacation journalière", 15500, 1),
    ]

    for code, categorie, intitule, montant, ordre in rows:
        BaremePrestation.objects.update_or_create(
            code=code,
            defaults={
                "categorie": categorie,
                "intitule": intitule,
                "montant": montant,
                "ordre": ordre,
                "active": True,
            },
        )


def unseed_baremes(apps, schema_editor):
    BaremePrestation = apps.get_model("prestation", "BaremePrestation")
    BaremePrestation.objects.filter(code__in=[
        "01", "02", "03", "04", "05", "06", "07", "08", "09", "10",
        "11", "12", "13", "14", "15", "16", "17", "18",
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('prestation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaremePrestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('categorie', models.CharField(choices=[('enseignement', 'Enseignement (par période académique)'), ('academique', 'Activités académiques (examens et autres)'), ('jury', 'Jury et soutenance'), ('logistique', 'Avantages logistiques')], max_length=30, verbose_name='Catégorie')),
                ('intitule', models.CharField(max_length=255, verbose_name='Intitulé')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant (CDF)')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Barème de prestation',
                'verbose_name_plural': 'Barèmes de prestation',
                'ordering': ['categorie', 'ordre', 'code'],
            },
        ),
        migrations.RunPython(seed_baremes, reverse_code=unseed_baremes),
    ]
