# Generated by Django 5.2.11 on 2026-04-07 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_alter_card_public_token'),
        ('prestation', '0002_baremeprestation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prestation', models.DateField(verbose_name='Date')),
                ('categorie', models.CharField(choices=[('enseignement', 'Enseignement (par période académique)'), ('academique', 'Activités académiques (examens et autres)'), ('jury', 'Jury et soutenance'), ('logistique', 'Avantages logistiques')], max_length=30, verbose_name='Catégorie')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant (CDF)')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bareme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestations', to='prestation.baremeprestation', verbose_name='Barème')),
                ('horaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestations', to='prestation.horaire', verbose_name='Horaire')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestations', to='cards.personnel', verbose_name='Personnel')),
            ],
            options={
                'verbose_name': 'Prestation',
                'verbose_name_plural': 'Prestations',
                'ordering': ['-date_prestation', '-created_at'],
            },
        ),
    ]
