# Generated by Django 5.2.11 on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestation', '0003_prestation'),
    ]

    operations = [
        migrations.AddField(
            model_name='baremeprestation',
            name='periode',
            field=models.CharField(
                choices=[
                    ('jour', 'Jour'),
                    ('heure', 'Heure'),
                    ('mois', 'Mois'),
                    ('memoire', 'Mémoire'),
                    ('bar', 'Bar'),
                    ('tfc', 'TFC'),
                    ('litre', 'Litre'),
                ],
                default='jour',
                max_length=20,
                verbose_name='Période',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='baremeprestation',
            name='categorie',
            field=models.CharField(
                choices=[
                    ('enseignement', 'Enseignement (par période académique)'),
                    ('academique', 'Activités académiques (examens et autres)'),
                    ('jury', 'Jury et soutenance'),
                    ('logistique', 'Avantages logistiques'),
                ],
                max_length=30,
                verbose_name='Type prestation',
            ),
        ),
        migrations.AlterField(
            model_name='prestation',
            name='categorie',
            field=models.CharField(
                choices=[
                    ('enseignement', 'Enseignement (par période académique)'),
                    ('academique', 'Activités académiques (examens et autres)'),
                    ('jury', 'Jury et soutenance'),
                    ('logistique', 'Avantages logistiques'),
                ],
                max_length=30,
                verbose_name='Type prestation',
            ),
        ),
    ]
