# Generated by Django 5.2.11 on 2026-05-19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestation', '0004_baremeprestation_periode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baremeprestation',
            name='code',
        ),
        migrations.AlterModelOptions(
            name='baremeprestation',
            options={
                'ordering': ['categorie', 'ordre', 'intitule'],
                'verbose_name': 'Barème de prestation',
                'verbose_name_plural': 'Barèmes de prestation',
            },
        ),
    ]
