# Generated by Django 5.2.11 on 2026-05-19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prestation', '0005_remove_baremeprestation_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnveloppeBudgetaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('mois', models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mois')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Montant de l'enveloppe (CDF)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enveloppe budgétaire',
                'verbose_name_plural': 'Enveloppes budgétaires',
                'ordering': ['-annee', '-mois'],
            },
        ),
        migrations.AddConstraint(
            model_name='enveloppebudgetaire',
            constraint=models.UniqueConstraint(fields=('annee', 'mois'), name='unique_enveloppe_annee_mois'),
        ),
        migrations.CreateModel(
            name='PaieMensuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total_valide', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='Total validé (CDF)')),
                ('validee_le', models.DateTimeField(auto_now_add=True, verbose_name='Validée le')),
                ('enveloppe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paie_validee', to='prestation.enveloppebudgetaire', verbose_name='Enveloppe budgétaire')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paies_mensuelles_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par')),
            ],
            options={
                'verbose_name': 'Paie mensuelle validée',
                'verbose_name_plural': 'Paies mensuelles validées',
                'ordering': ['-validee_le'],
            },
        ),
    ]
