# Generated by Django 5.2.11 on 2026-05-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestation', '0006_enveloppebudgetaire_paiemensuelle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiemensuelle',
            options={'ordering': ['-validee_le'], 'verbose_name': 'Clôture de paie mensuelle', 'verbose_name_plural': 'Clôtures de paie mensuelle'},
        ),
    ]
