# Generated by Django 5.2.10 on 2026-01-23 18:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('evaluations', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliberation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_deliberation', models.DateField(verbose_name='Date de délibération')),
                ('statut', models.CharField(choices=[('en_preparation', 'En préparation'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('verrouillee', 'Verrouillée')], default='en_preparation', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes du jury')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membres_jury', models.ManyToManyField(blank=True, related_name='deliberations_membre', to=settings.AUTH_USER_MODEL, verbose_name='Membres du jury')),
                ('president_jury', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliberations_president', to=settings.AUTH_USER_MODEL, verbose_name='Président du jury')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliberations', to='evaluations.session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Délibération',
                'verbose_name_plural': 'Délibérations',
                'ordering': ['-date_deliberation'],
                'unique_together': {('session',)},
            },
        ),
        migrations.CreateModel(
            name='DecisionJury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('admis', 'Admis'), ('admis_avec_dettes', 'Admis avec dettes'), ('redouble', 'Redouble'), ('exclu', 'Exclu'), ('ajourne', 'Ajourné'), ('report', 'Report')], max_length=20, verbose_name='Décision')),
                ('moyenne_semestre', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))], verbose_name='Moyenne du semestre')),
                ('credits_obtenus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Crédits obtenus')),
                ('credits_totaux', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Crédits totaux')),
                ('rang', models.IntegerField(blank=True, null=True, verbose_name='Rang')),
                ('mention', models.CharField(blank=True, choices=[('', 'Sans mention'), ('passable', 'Passable'), ('assez_bien', 'Assez Bien'), ('bien', 'Bien'), ('tres_bien', 'Très Bien')], max_length=20, verbose_name='Mention')),
                ('notes_jury', models.TextField(blank=True, null=True, verbose_name='Notes du jury')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions_jury', to='students.student', verbose_name='Étudiant')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions_jury', to='students.inscription', verbose_name='Inscription')),
                ('deliberation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='deliberations.deliberation', verbose_name='Délibération')),
            ],
            options={
                'verbose_name': 'Décision du jury',
                'verbose_name_plural': 'Décisions du jury',
                'ordering': ['deliberation', 'rang', 'etudiant'],
                'unique_together': {('deliberation', 'etudiant')},
            },
        ),
        migrations.CreateModel(
            name='ParametresLMD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seuil_validation', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))], verbose_name='Seuil de validation (/20)')),
                ('compensation_intra_ue', models.BooleanField(default=True, verbose_name='Compensation intra-UE')),
                ('compensation_intra_semestre', models.BooleanField(default=True, verbose_name='Compensation intra-semestre')),
                ('compensation_annuelle', models.BooleanField(default=True, verbose_name='Compensation annuelle')),
                ('capitalisation_ue', models.BooleanField(default=True, verbose_name='Capitalisation des UE')),
                ('capitalisation_ec', models.BooleanField(default=True, verbose_name='Capitalisation des EC')),
                ('passage_avec_dettes', models.BooleanField(default=True, verbose_name='Passage avec dettes')),
                ('seuil_credits_minimum', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Seuil crédits minimum pour passage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametres_lmd', to='academics.promotion', verbose_name='Promotion')),
            ],
            options={
                'verbose_name': 'Paramètres LMD',
                'verbose_name_plural': 'Paramètres LMD',
                'unique_together': {('promotion',)},
            },
        ),
    ]
