# Generated by Django 5.0.4 on 2026-07-06 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_uniteenseignement_filiere'),
        ('deliberations', '0003_deliberation_annuelle'),
        ('evaluations', '0005_deliberation_cycle_master'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliberation',
            name='annee_academique_m1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliberations_cycle_m1', to='academics.anneeacademique', verbose_name='Année académique Master 1'),
        ),
        migrations.AlterField(
            model_name='deliberation',
            name='type_deliberation',
            field=models.CharField(choices=[('semestrielle', 'Semestrielle'), ('annuelle', 'Annuelle'), ('cycle_master', 'Cycle Master (M1+M2)')], default='semestrielle', max_length=20, verbose_name='Type'),
        ),
        migrations.AddConstraint(
            model_name='deliberation',
            constraint=models.UniqueConstraint(condition=models.Q(('type_deliberation', 'cycle_master')), fields=('promotion', 'annee_academique_m1', 'annee_academique'), name='delib_unique_cycle_master'),
        ),
    ]
