# Generated by Django 5.0.4 on 2026-07-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliberations', '0004_deliberation_cycle_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionjury',
            name='decision',
            field=models.CharField(choices=[('admis', 'Admis'), ('admis_compensation', 'Admis par compensation'), ('admis_avec_dettes', 'Admis avec dettes'), ('defaillant', 'Défaillant'), ('redouble', 'Redouble'), ('exclu', 'Exclu'), ('ajourne', 'Ajourné'), ('report', 'Report')], max_length=20, verbose_name='Décision'),
        ),
    ]
