# Generated by Django 5.2.10 on 2026-07-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliberations', '0005_decisions_jury_barème'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliberation',
            name='membres_jury_noms',
            field=models.TextField(blank=True, help_text='Un nom par ligne (affiché dans la fiche délibération et le PV).', verbose_name='Membres du jury (noms libres)'),
        ),
        migrations.AddField(
            model_name='deliberation',
            name='president_jury_nom',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nom affiché du président'),
        ),
        migrations.AddField(
            model_name='deliberation',
            name='secretaire_jury_nom',
            field=models.CharField(blank=True, max_length=200, verbose_name='Secrétaire du jury'),
        ),
    ]
