# Generated by Django 5.2.10 on 2026-01-23 18:04

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliberations', '0001_initial'),
        ('evaluations', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDocumentGenere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('template_pdf', models.CharField(blank=True, max_length=200, null=True, verbose_name='Template PDF')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Type de document généré',
                'verbose_name_plural': 'Types de documents générés',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DocumentGenere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=documents.models.document_generated_path, verbose_name='Fichier PDF')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deliberation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_generes', to='deliberations.deliberation', verbose_name='Délibération')),
                ('etudiant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_generes', to='students.student', verbose_name='Étudiant')),
                ('genere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
                ('inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_generes', to='students.inscription', verbose_name='Inscription')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents_generes', to='evaluations.session', verbose_name='Session')),
                ('type_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.typedocumentgenere', verbose_name='Type de document')),
            ],
            options={
                'verbose_name': 'Document généré',
                'verbose_name_plural': 'Documents générés',
                'ordering': ['-date_generation'],
            },
        ),
    ]
