# Generated by Django 5.0.4 on 2026-06-26 13:29

import django.db.models.deletion
import django.utils.timezone
import documents.models
from django.conf import settings
from django.db import migrations, models


def seed_types_attestation(apps, schema_editor):
    TypeAttestation = apps.get_model('documents', 'TypeAttestation')
    types = [
        ('scolarite', 'Attestation de scolarité', 'Certifie l\'inscription régulière de l\'étudiant.', 1),
        ('inscription', 'Attestation d\'inscription', 'Certifie l\'inscription administrative.', 2),
        ('reussite', 'Attestation de réussite', 'Certifie la réussite aux épreuves.', 3),
        ('stage', 'Attestation de stage', 'Certifie un stage effectué.', 4),
    ]
    for code, nom, description, ordre in types:
        TypeAttestation.objects.get_or_create(
            code=code,
            defaults={'nom': nom, 'description': description, 'ordre': ordre, 'active': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('students', '0009_alter_student_numero_etudiant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAttestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('ordre', models.IntegerField(default=1, verbose_name="Ordre d'affichage")),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': "Type d'attestation",
                'verbose_name_plural': "Types d'attestation",
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Numéro')),
                ('date_delivrance', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date de délivrance')),
                ('lieu_delivrance', models.CharField(default='Brazzaville', max_length=200, verbose_name='Lieu de délivrance')),
                ('objet', models.TextField(blank=True, help_text='Remplace le texte standard si renseigné.', null=True, verbose_name='Texte personnalisé')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes internes')),
                ('fichier', models.FileField(blank=True, null=True, upload_to=documents.models.attestation_pdf_path, verbose_name='Fichier PDF')),
                ('date_generation', models.DateTimeField(blank=True, null=True, verbose_name='Date de génération PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attestations_generees', to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='students.inscription', verbose_name='Inscription')),
                ('type_attestation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attestations', to='documents.typeattestation', verbose_name="Type d'attestation")),
            ],
            options={
                'verbose_name': 'Attestation',
                'verbose_name_plural': 'Attestations',
                'ordering': ['-date_delivrance', '-created_at'],
            },
        ),
        migrations.RunPython(seed_types_attestation, migrations.RunPython.noop),
    ]
