# Generated by Django 5.0.4 on 2026-06-18 14:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_uniteenseignement_filiere'),
        ('deliberations', '0002_deliberation_promotion'),
        ('evaluations', '0003_increase_session_code_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deliberation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='decisionjury',
            name='credits_semestre1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Crédits semestre 1'),
        ),
        migrations.AddField(
            model_name='decisionjury',
            name='credits_semestre2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Crédits semestre 2'),
        ),
        migrations.AddField(
            model_name='decisionjury',
            name='moyenne_semestre1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))], verbose_name='Moyenne semestre 1'),
        ),
        migrations.AddField(
            model_name='decisionjury',
            name='moyenne_semestre2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))], verbose_name='Moyenne semestre 2'),
        ),
        migrations.AddField(
            model_name='deliberation',
            name='annee_academique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliberations_annuelles', to='academics.anneeacademique', verbose_name='Année académique'),
        ),
        migrations.AddField(
            model_name='deliberation',
            name='semestre1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliberations_annuelles_s1', to='academics.semestre', verbose_name='Semestre 1'),
        ),
        migrations.AddField(
            model_name='deliberation',
            name='semestre2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliberations_annuelles_s2', to='academics.semestre', verbose_name='Semestre 2'),
        ),
        migrations.AddField(
            model_name='deliberation',
            name='type_deliberation',
            field=models.CharField(choices=[('semestrielle', 'Semestrielle'), ('annuelle', 'Annuelle')], default='semestrielle', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='decisionjury',
            name='moyenne_semestre',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))], verbose_name='Moyenne du semestre / annuelle'),
        ),
        migrations.AlterField(
            model_name='deliberation',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliberations', to='evaluations.session', verbose_name='Session'),
        ),
        migrations.AddConstraint(
            model_name='deliberation',
            constraint=models.UniqueConstraint(condition=models.Q(('type_deliberation', 'semestrielle')), fields=('session', 'promotion'), name='delib_unique_session_promotion'),
        ),
        migrations.AddConstraint(
            model_name='deliberation',
            constraint=models.UniqueConstraint(condition=models.Q(('type_deliberation', 'annuelle')), fields=('promotion', 'annee_academique', 'semestre1', 'semestre2'), name='delib_unique_annuelle'),
        ),
    ]
