# Generated by Django 5.0.4 on 2026-09-22 16:51

from django.db import migrations, models


def seed_unikin(apps, schema_editor):
    Etablissement = apps.get_model('config', 'Etablissement')
    Etablissement.objects.get_or_create(
        code='UNIKIN',
        defaults={
            'nom': 'Université de Kinshasa',
            'statut_juridique': 'public',
            'categorie': 'universite',
            'province': 'Kinshasa',
            'ville': 'Kinshasa',
            'adresse': 'Mont-Amba, Kinshasa',
            'tutelle': "Ministère de l'Enseignement Supérieur et Universitaire",
            'phase': 'pilote',
            'actif': True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Sigle')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom officiel')),
                ('statut_juridique', models.CharField(choices=[('public', 'Public'), ('prive', 'Privé')], max_length=10, verbose_name='Statut juridique')),
                ('categorie', models.CharField(choices=[('universite', 'Université'), ('institut_superieur', 'Institut supérieur'), ('isp', 'Institut supérieur pédagogique'), ('ist', 'Institut supérieur technique'), ('istm', 'Institut supérieur des techniques médicales'), ('ecole_superieure', 'École supérieure'), ('grande_ecole', 'Grande école')], max_length=30, verbose_name='Catégorie')),
                ('province', models.CharField(choices=[('Kinshasa', 'Kinshasa'), ('Kongo-Central', 'Kongo-Central'), ('Kwango', 'Kwango'), ('Kwilu', 'Kwilu'), ('Mai-Ndombe', 'Mai-Ndombe'), ('Équateur', 'Équateur'), ('Mongala', 'Mongala'), ('Nord-Ubangi', 'Nord-Ubangi'), ('Sud-Ubangi', 'Sud-Ubangi'), ('Tshuapa', 'Tshuapa'), ('Tshopo', 'Tshopo'), ('Bas-Uele', 'Bas-Uele'), ('Haut-Uele', 'Haut-Uele'), ('Ituri', 'Ituri'), ('Nord-Kivu', 'Nord-Kivu'), ('Sud-Kivu', 'Sud-Kivu'), ('Maniema', 'Maniema'), ('Haut-Katanga', 'Haut-Katanga'), ('Haut-Lomami', 'Haut-Lomami'), ('Lualaba', 'Lualaba'), ('Tanganyika', 'Tanganyika'), ('Lomami', 'Lomami'), ('Kasaï', 'Kasaï'), ('Kasaï-Central', 'Kasaï-Central'), ('Kasaï-Oriental', 'Kasaï-Oriental'), ('Sankuru', 'Sankuru')], max_length=40, verbose_name='Province')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web')),
                ('tutelle', models.CharField(default="Ministère de l'Enseignement Supérieur et Universitaire", max_length=200, verbose_name='Tutelle')),
                ('numero_agrement', models.CharField(blank=True, help_text='Obligatoire pour un établissement privé.', max_length=80, verbose_name="Numéro d'agrément")),
                ('date_agrement', models.DateField(blank=True, null=True, verbose_name="Date d'agrément")),
                ('promoteur', models.CharField(blank=True, help_text='Personne morale ou physique, pour un établissement privé.', max_length=200, verbose_name='Promoteur')),
                ('phase', models.CharField(choices=[('pilote', 'Pilote'), ('extension', 'Extension'), ('generalisation', 'Généralisation')], default='extension', max_length=20, verbose_name='Phase de déploiement')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Établissement',
                'verbose_name_plural': 'Établissements',
                'ordering': ['nom'],
            },
        ),
        migrations.RunPython(seed_unikin, migrations.RunPython.noop),
    ]
