# Generated by Django 5.0.4 on 2026-09-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_etablissement_national'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='logo',
            field=models.ImageField(blank=True, help_text='Image PNG, JPEG ou WebP, 2 Mo au plus.', null=True, upload_to='etablissements/logos/', verbose_name='Logo'),
        ),
    ]
